CREATE TABLE [dbo].[CardFace]
(
	[CardId] INT NOT NULL,
	[FaceId] INT NOT NULL,
	[Url] NVARCHAR(450) NOT NULL,
	PRIMARY KEY([CardId], [FaceId]),
	CONSTRAINT FK_CardFace_CardId FOREIGN KEY (CardId) REFERENCES Card(Id) ON DELETE CASCADE,
	CONSTRAINT FK_CardFace_FaceId FOREIGN KEY (FaceId) REFERENCES Face(Id) ON DELETE CASCADE
)
